### ISSUE TITLE
PDF compiled by latexmk has only 6 pages, no solutions

### ISSUE THREAD

**Issue by adaptNYP** [wojtask/clrs4e-solutions#1564]
Hi,

I did `latexmk -pdf clrs4e-solutions.tex` after cloning the repo on my local machine, but the PDF output has only 6 pages, with no solutions. It has a cover page, and the **Appendix: Mathematical Background**, that's all.

May I know how to get the full set of solutions?

Thanks!

**Comment by wojtask** [comment]
Hi,

Thank you for your interest!
The project has just started, and I'm currently migrating my solutions from
the legacy project, where I solved around a half of the book (2nd edition,
in Polish) - see README for details.
As of today, there are only 4 solutions in Appendix A. More to follow,
please stay tuned.
Also, please let me know if you have any other issues with compiling the
document locally.

Krzysztof
