### ISSUE TITLE
Only the 4th chapter is generated into pdf

### ISSUE THREAD

**Issue by peter-simon** [wojtask/clrs4e-solutions#1588]
In commit 6b9d9319e66db6033afceb28fb9595cdcca9ece6 the changes made in the clrs4e-solutions.tex file (commenting) prevent most of the already created solutions from being generated into the .pdf.

**Comment by wojtask** [comment]
Thanks for reporting that. I mistakenly commited the commented imports in the main file when I started working on Chapter 4. I am going to get back to regular work on it soon.
